project_id = "oqklfnxpcxpqddakwloh"

[functions.create-user]
verify_jwt = false

[functions.update-user]
verify_jwt = false

[functions.reset-user-password]
verify_jwt = false

[functions.send-email]
verify_jwt = false

[functions.send-password-reset]
verify_jwt = false
